Module1 task3
htmlacademy-ecmascript/1387351-big-trip-14 pull request #3
Opened 2021-03-30 18:56 UTC by MblWa

2021-03-30 23:03 UTC, AlexMasterov requested changes

2021-03-30 23:03 UTC, AlexMasterov commented on src/view/trip-info-price.js
> +export const createTripInfoPriceTemplate = () => {
<details>
<summary>view/trip-info-price.js</summary>

https://github.com/htmlacademy-ecmascript/1387351-big-trip-14/blob/cfb0021e6f587812d0d7b4a8d0f7fdaf4fbc9d4f/src/view/trip-info-price.js#L1-L4
</details>

<details>
<summary>Покажи как упростить</summary>

```js
 export const createTripInfoPriceTemplate = () => ( 
   `<p class="trip-info__cost"> 
     Total: &euro;&nbsp;<span class="trip-info__cost-value">1230</span>
   </p>`
);
```

Скобки группировки выражений `()` здесь необязательны, но могут использоваться чтобы на одном уровне выровнять теги разметки, что так же может помочь некоторым редакторам/IDE с их автоматическим форматированием.

Используй далее скобки `()` с пониманием.
</details>

2021-04-01 16:43 UTC, MblWa commented on src/main.js
> +
Согласен, именование, как waypoint, лучше подходит.

2021-04-01 16:55 UTC, MblWa commented on src/main.js
> +const EVENTS_QTY = 3;
Мне правда казалось, что сокращение QTY от "количества" хорошо описывает верхнюю границу цикла и само по себе является распространенным. [Вот немного другой результат поиска этого сокращения, если не привязываться именно к events/event](https://github.com/search?q=*_QTY&type=code), но это не принципиально для меня. И, как я понимаю, временно, с точки зрения разработки этого проекта =)

2021-04-01 17:01 UTC, MblWa commented on src/main.js
> +for (let i = 0; i < EVENTS_QTY; i += 1) {
Я поменял на i++, т. к. меньше вопросов вызывает эта запись, а требования airbnb не вводились в проекте =)

2021-04-01 17:07 UTC, MblWa commented on src/main.js
> +render(siteEventsListElement, createNewEventTemplate(), 'beforeend');
Почему-то в требованиях в ДЗ указано [компонент «Форма редактирования» должен располагаться первым в списке.](https://up.htmlacademy.ru/ecmascript/14/tasks/3). Но логичнее-то как раз твой вариант. Я переделал. Вероятно, ошибку допустили в требованиях.

2021-04-01 17:14 UTC, MblWa commented on src/main.js
> +import {createEditEventTemplate} from './view/event-edit.js';
Согласен, не досмотрел это место.

2021-04-01 17:21 UTC, MblWa commented on src/view/trip-info-price.js
> +export const createTripInfoPriceTemplate = () => {
Вопросов нет, исправил.

2021-04-01 17:25 UTC, MblWa commented on src/main.js
> +const siteHeaderElement = document.querySelector('.page-header');
С одной стороны, да, можно было бы этим заниматься. С другой стороны, нет. Я лучше займусь ещё чем-нибудь ;)
Переименовал.

2021-04-01 17:26 UTC, MblWa commented on webpack.config.js
> +const staticDirPath = path.resolve(__dirname, 'public');
(.)(.)

2021-04-01 23:01 UTC, AlexMasterov approved these changes
Пожалуйста, важное замечание в остатке доработай при выполнении следующего задания. 

В след. задание прошу постараться не усложнять в одиночку, а посоветоваться со мной 😄

> По ходу продвижения по заданием возрастает риск появления костыльных решений в самих основах приложения, которые могут сильно усложнить реализацию ТЗ и отнять много времени

2021-04-01 23:01 UTC, merged

2021-04-04 15:11 UTC, MblWa commented on src/util.js
> +export const insertButtonsToFormTemplate = (place, string) => {
В который раз убеждаюсь, что не нужно писать код по ночам — рождаются монстры и велосипеды. Спасибо за подсказку, я не подумал в эту сторону вообще. Крутой приём. Сейчас исправлю.