Module2 task1
htmlacademy-ecmascript/1387351-big-trip-14 pull request #4
Opened 2021-04-07 21:52 UTC by MblWa

2021-04-08 17:10 UTC, AlexMasterov requested changes
По результатам первой проверки следует подумать об устной консультации 😃

2021-04-08 17:10 UTC, AlexMasterov commented on src/view/point.js
> +export const createPointTemplate = ({ startTime, endTime, isFavourite, type, price, destinationCity, offers }) => (
<details>
<summary>view/point.js</summary>

https://github.com/htmlacademy-ecmascript/1387351-big-trip-14/blob/d6c763b1d351f3685d2eb48a33b065c5fb0a8b50/src/view/point.js#L51
https://github.com/htmlacademy-ecmascript/1387351-big-trip-14/blob/d6c763b1d351f3685d2eb48a33b065c5fb0a8b50/src/view/point.js#L58
https://github.com/htmlacademy-ecmascript/1387351-big-trip-14/blob/d6c763b1d351f3685d2eb48a33b065c5fb0a8b50/src/view/point.js#L60
</details>

Для атрибута `datetime` используется невалидное значение даты времени.

Нужно использовать значение даты (_в формате ISO_) из данных.

<details>

<summary>Покажи что пишут спецификации</summary>

См. [спецификацию](https://html.spec.whatwg.org/multipage/common-microsyntaxes.html#dates-and-times):
> Этот атрибут специфицирует время и дату и **должен быть допустимой датой с возможным дополнительным указанием времени**

См. также [datetime](http://htmlbook.ru/html/time/datetime):
> Дата и время задается в международном формате [ISO 8601](https://ru.wikipedia.org/wiki/ISO_8601). Примеры <...>

См. также тренажер по базовому HTML: [Тег time, дата и время](https://htmlacademy.ru/courses/301/run/15).

Для этого можно использовать готовое API: [Date.p.`toISOString`](https://developer.mozilla.org/ru/docs/Web/JavaScript/Reference/Global_Objects/Date/toISOString) (= ISO 8601).
</details>

2021-04-11 11:13 UTC, MblWa commented on src/view/info-route.js
> +      : routeArray.join(' &mdash '),
Исправил.

2021-04-11 11:25 UTC, MblWa commented on src/view/info-price.js
> +const calculatePrice = (points) => {
Переделал.

2021-04-12 10:14 UTC, AlexMasterov requested changes
Нужно доработать замечания в остатке.

> Необязательные замечания можешь игнорировать

2021-06-01 21:05 UTC, merged